<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';




// autoload.php @generated by typo3/class-alias-loader

require_once __DIR__ . '/composer/autoload_alias_loader_real.php';

return ClassAliasLoaderInita201f904eeb10b8d569ada41140697b7::initializeClassAliasLoader(ComposerAutoloaderInita201f904eeb10b8d569ada41140697b7::getLoader());
