<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_front_edit"
 *
 * Auto generated by Extension Builder 2014-08-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Article Edit',
	'description' => 'Article Management',
	'category' => 'plugin',
	'author' => 'WangHongBin',
	'author_email' => 'info@whongbin.cn',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.2.0',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);