<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'SFC\\Staticfilecache\\' => array($typo3InstallDir . 'typo3conf/ext/staticfilecache/Classes'),
    'SIMONKOEHLER\\Slug\\' => array($typo3InstallDir . 'typo3conf/ext/slug/Classes'),
    'Sll\\Common\\' => array($typo3InstallDir . 'typo3conf/ext/common/Classes'),
    'Sll\\SllFileManager\\' => array($typo3InstallDir . 'typo3conf/ext/sll_file_manager/Classes'),
    'Sll\\SllFriendLink\\' => array($typo3InstallDir . 'typo3conf/ext/sll_friend_link/Classes'),
    'Sll\\SllPlugin\\' => array($typo3InstallDir . 'typo3conf/ext/sll_plugin/Classes'),
    'Sll\\SllSnow\\' => array($typo3InstallDir . 'typo3conf/ext/sll_snow/Classes'),
    'Yyy\\GeneralBusinessBackendPackage\\' => array($typo3InstallDir . 'typo3conf/ext/general_business_backend_package/Classes'),
    'Yyy\\GeneralBusinessFrontendPackage\\' => array($typo3InstallDir . 'typo3conf/ext/general_business_frontend_package/Classes'),
);
