<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sll_fe_user"
 *
 * Auto generated by Extension Builder 2019-11-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Front User Manager',
    'description' => '用户管理扩展',
    'category' => 'plugin',
    'author' => '三里林',
    'author_email' => 'info@whongbin.cn',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
